### ISSUE TITLE
Array destructuring in v-for

### ISSUE THREAD

**Issue by dimensi** [vuejs/vue-loader#1062]
### Version
13.5.0

### Reproduction link
[https://codesandbox.io/s/l72vorr44m](https://codesandbox.io/s/l72vorr44m)

### Steps to reproduce
1. set directive `v-for="([rank, text, percent], index) in refTable"`
2. get error

### What is expected?
Expect work

### What is actually happening?
Error

---
I have some issue like here https://github.com/vuejs/vue-loader/issues/630
```
Module build failed: SyntaxError: Unexpected token (1:864)
    at Parser.pp$4.raise (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:2610:13)
    at Parser.pp.unexpected (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:637:8)
    at Parser.pp$2.parseBindingAtom (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1602:10)
    at Parser.pp$2.parseMaybeDefault (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1640:23)
    at Parser.pp$2.parseBindingList (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1625:25)
    at Parser.pp$1.parseFunctionParams (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1189:22)
    at Parser.pp$1.parseFunction (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1176:8)
    at Parser.pp$3.parseExprAtom (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:2082:17)
    at Parser.parseExprAtom (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parseExprList (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:2528:20)
    at Parser.pp$3.parseSubscripts (/home/dimensi/projects/sdm-front-spa/node_modules/vue-template-es2015-compiler/buble.js:1983:29)
 @ ./src/views/pages/Stocks.vue 10:0-366
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

**Comment by Jinjiang** [comment]
Just remove the bracket: `[foo, bar], index in arr` is fine.

**Comment by Jinjiang** [comment]
@defcc Is it possible to automatically remove the brackets through `vue-template-compiler`? Maybe you can help this :-)
Thanks.

**Comment by dimensi** [comment]
@yyx990803 @Jinjiang Maybe close this?
