### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'vue' of undefined

### ISSUE THREAD

**Issue by 4096void** [vuejs/vue-loader#1177]
Module build failed: TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/some_path/node_modules/vue-loader/lib/loader.js:57:29)

**Comment by thomasklein** [comment]
Hi! You are using Webpack 4?

**Comment by 4096void** [comment]
Sorry, I forget update vue-loader@latest

**Comment by phalconVee** [comment]
i am having same issue:

App.vue:1 Uncaught Error: Module build failed: TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (C:\xampp\htdocs\ci_vue\ci_vue\node_modules\vue-loader\lib\loader.js:61:18)
    at Object.module.exports (C:\xampp\htdocs\ci_vue\ci_vue\node_modules\vue-loader\lib\loader.js:61:18)
    at eval (webpack-internal:///./src/App.vue:1:7)
    at Object../src/App.vue (http://localhost/ci_vue/ci_vue/src/dist/build.js:392:1)
    at __webpack_require__ (http://localhost/ci_vue/ci_vue/src/dist/build.js:20:30)
    at eval (webpack-internal:///./src/main.js:3:62)
    at Object../src/main.js (http://localhost/ci_vue/ci_vue/src/dist/build.js:415:1)
    at __webpack_require__ (http://localhost/ci_vue/ci_vue/src/dist/build.js:20:30)
    at http://localhost/ci_vue/ci_vue/src/dist/build.js:69:18
    at http://localhost/ci_vue/ci_vue/src/dist/build.js:72:10

**Comment by wilmaribg** [comment]
for webcpack ^4.x 

npm install vue-loader@14.2.2

**Comment by SmalldyCL1314** [comment]
> my webpack version:
> 
> "webpack": "^3.11.0",

have you resolved this question?

**Comment by bcdbuddy** [comment]
have the same problem

**Comment by franksoong** [comment]
any solution on this?

**Comment by pjaer** [comment]
> any solution on this issue?

Worked for me to update loader(s) to latest versions

**Comment by shaohung001** [comment]
solve to downgrade sass-load to 7.1.0, worked piece:
```
sass-loader: 7.1.0
webpack: 3.6.0
vue-loader:  13.3.0
vue: 2.5.2
```

**Comment by realtebo** [comment]
I solved upgrading vue-loader to ^15.7.1 and removing explicit declaration of css-loader dependency

**Comment by jigark17** [comment]
i am using  "webpack": "^4.41.6",

Module build failed: TypeError: Cannot read property 'vue' of undefined
at Object.module.exports (/some_path/node_modules/vue-loader/lib/loader.js:57:29)

give me the solution

**Comment by destinyvoilet** [comment]
> for webcpack ^4.x
> 
> npm install vue-loader@14.2.2

what for webpack ^5.x ?

**Comment by dev-meta** [comment]
> > for webcpack ^4.x
> > npm install vue-loader@14.2.2
> 
> what for webpack ^5.x ?

v15 is ok

**Comment by Sandyzhao19** [comment]
npm install vue-loader@15 works for webpack ^5.x

**Comment by Norman5353** [comment]
i have this issue as well , several times downgraded the bootstrap and bootstrap-vue but not solved 

"dependencies": {
    "bootstrap": "^4.6.0",
    "bootstrap-vue": "^2.23.1",
    "core-js": "^3.8.3",
    "vue": "^3.2.13"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "webpack": "^5.89.0",
    "webpack-cli": "^5.1.4"

Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'version')
TypeError: Cannot read properties of undefined (reading 'version')
    at eval (webpack-internal:///./node_modules/bootstrap-vue/esm/vue.js:90:58)
    at ./node_modules/bootstrap-vue/esm/vue.js (http://localhost:8081/js/chunk-vendors.js:3417:1)
    at __webpack_require__ (http://localhost:8081/js/app.js:491:33)
    at fn (http://localhost:8081/js/app.js:725:21)
    at eval (webpack-internal:///./node_modules/bootstrap-vue/esm/constants/events.js:66:62)
    at ./node_modules/bootstrap-vue/esm/constants/events.js (http://localhost:8081/js/chunk-vendors.js:2372:1)
    at __webpack_require__ (http://localhost:8081/js/app.js:491:33)
    at fn (http://localhost:8081/js/app.js:725:21)
    at eval (webpack-internal:///./node_modules/bootstrap-vue/esm/components/alert/alert.js:9:76)
    at ./node_modules/bootstrap-vue/esm/components/alert/alert.js (http://localhost:8081/js/chunk-vendors.js:84:1)

**Comment by SashankSingh97** [comment]
> i have this issue as well , several times downgraded the bootstrap and bootstrap-vue but not solved
> 
> "dependencies": { "bootstrap": "^4.6.0", "bootstrap-vue": "^2.23.1", "core-js": "^3.8.3", "vue": "^3.2.13" }, "devDependencies": { "@babel/core": "^7.12.16", "@babel/eslint-parser": "^7.12.16", "@vue/cli-plugin-babel": "~5.0.0", "@vue/cli-plugin-eslint": "~5.0.0", "@vue/cli-service": "~5.0.0", "eslint": "^7.32.0", "eslint-plugin-vue": "^8.0.3", "webpack": "^5.89.0", "webpack-cli": "^5.1.4"
> 
> Uncaught runtime errors: × ERROR Cannot read properties of undefined (reading 'version') TypeError: Cannot read properties of undefined (reading 'version') at eval (webpack-internal:///./node_modules/bootstrap-vue/esm/vue.js:90:58) at ./node_modules/bootstrap-vue/esm/vue.js (http://localhost:8081/js/chunk-vendors.js:3417:1) at **webpack_require** (http://localhost:8081/js/app.js:491:33) at fn (http://localhost:8081/js/app.js:725:21) at eval (webpack-internal:///./node_modules/bootstrap-vue/esm/constants/events.js:66:62) at ./node_modules/bootstrap-vue/esm/constants/events.js (http://localhost:8081/js/chunk-vendors.js:2372:1) at **webpack_require** (http://localhost:8081/js/app.js:491:33) at fn (http://localhost:8081/js/app.js:725:21) at eval (webpack-internal:///./node_modules/bootstrap-vue/esm/components/alert/alert.js:9:76) at ./node_modules/bootstrap-vue/esm/components/alert/alert.js (http://localhost:8081/js/chunk-vendors.js:84:1)

do you find any solution ?
