### ISSUE TITLE
[15.0.0-beta.2] VueLoaderPlugin Error: no matching rule for vue files are found.

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-loader#1202]
### Version
15.0.0-beta.2

### Reproduction link
n/a

### Steps to reproduce

I noticed that i am getting this error when rule for `.vue` files contains `include` option with absolute folder path. Example of failing webpack config

```js
const path = require('path');
const { VueLoaderPlugin } = require('vue-loader');

const src = path.resolve(__dirname, 'src');

module.exports = {
  entry: {
    app: path.join(src, 'index.js'),
  },
  output: {
    publicPath: '/',
    path: path.resolve(__dirname, 'build'),
    filename: '[name].bundle.js',
    chunkFilename: '[id].[name].chunk.js',
  },
  resolve: {
    extensions: [
      '.js',
      '.vue',
    ],
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: src,
        loader: 'babel-loader',
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        include: src, // <-- causes the error
        options: {
          preserveWhitespace: false,
        },
      },
    ],
  },
  plugins: [
    new VueLoaderPlugin(),
  ],
};

```

Full log:

```
Error: VueLoaderPlugin Error: no matching rule for vue files are found.
    at VueLoaderPlugin.apply (C:\dev\vue-loader-next\node_modules\vue-loader\lib\plugin.js:19:13)
    at Compiler.apply (C:\dev\vue-loader-next\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\dev\vue-loader-next\node_modules\webpack\lib\webpack.js:33:19)
    at processOptions (C:\dev\vue-loader-next\node_modules\webpack\bin\webpack.js:335:15)
    at yargs.parse (C:\dev\vue-loader-next\node_modules\webpack\bin\webpack.js:397:2)
    at Object.Yargs.self.parse (C:\dev\vue-loader-next\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\dev\vue-loader-next\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

Webpack version **3.11.0**

### What is expected?
I would like to bundle my project without error.

### What is actually happening?
Webpack throws mentioned error

**Comment by sqal** [comment]
Sorry for duplicate https://github.com/vuejs/vue-loader/issues/1201 :(

**Comment by Loilo** [comment]
That was a quick sequence of issues. 😁

**Comment by yyx990803** [comment]
fixed in 2be5507

**Comment by Heartnett** [comment]
@yyx990803 Please document the use of **VueLoaderPlugin**

**Comment by Loilo** [comment]
Are you looking for the [vue-loader docs](http://vue-loader.vuejs.org/)?

**Comment by Heartnett** [comment]
Thanks!

**Comment by zhangshengpeng** [comment]
I got the same error message when I try to let the 'vue-loader' in oneOf：

`rules: [
      {
        oneOf: [
          {
            test: /\.vue$/,
            include: path.resolve(__dirname, 'src'),
            loader: 'vue-loader'
          }
        ]
    }
 ]`

error message :
Error: [VueLoaderPlugin Error] No matching rule for .vue files found.
Make sure there is at least one root-level rule that matches .vue or .vue.html files.
