### ISSUE TITLE
Cannot assign to read only property '0' of string 'vue-loader'

### ISSUE THREAD

**Issue by sgehrman** [vuejs/vue-loader#1260]
### Version
15.0.0

### Reproduction link
[https://codepen.io/autumnwoodberry/pen/jLPKWv?editors=1010](https://codepen.io/autumnwoodberry/pen/jLPKWv?editors=1010)

### Steps to reproduce
none

### What is expected?
should work

### What is actually happening?
TypeError: Cannot assign to read only property '0' of string 'vue-loader'
    at VueLoaderPlugin.apply (/home/sgehrman/github/electron-store/node_modules/vue-loader/lib/plugin.js:97:42)
    at webpack (/home/sgehrman/github/electron-store/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/home/sgehrman/github/electron-store/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/home/sgehrman/github/electron-store/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/home/sgehrman/github/electron-store/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /home/sgehrman/github/electron-store/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/home/sgehrman/github/electron-store/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)

---

**Comment by yyx990803** [comment]
Please follow the instructions and provide a valid reproduction. If you can't respect the rules and the maintainers' time, don't expect anything other than a closed issue.
