### ISSUE TITLE
loaderContext.emitError is not a function

### ISSUE THREAD

**Issue by martonx** [vuejs/vue-loader#1287]
### Version
15.0.0

### Reproduction link
[https://github.com/martonx/travellerRepro](https://github.com/martonx/travellerRepro)

### Steps to reproduce
run npm install then webpack --mode development

### What is expected?
My vue and scss files should compiled. Before update vue-loader from 14 to 15. It worked.

### What is actually happening?
TypeError: loaderContext.emitError is not a function
    at new module.exports (C:\work\Traveller\Traveller.Web.Portal\node_modules\vue-loader\lib\index.js:19:19)
    at module.exports (C:\work\Traveller\Traveller.Web.Portal\webpack.config.js:57:13)
    at handleFunction (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\prepareOptions.js:23:13)
    at prepareOptions (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\prepareOptions.js:9:5)
    at requireConfig (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\convert-argv.js:136:14)
    at C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\webpack.js:239:39)
    at Object.parse (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
    at C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\webpack.js:217:8
    at Object.<anonymous> (C:\work\Traveller\Traveller.Web.Portal\node_modules\webpack-cli\bin\webpack.js:514:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports.filename (C:\Users\lajos\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\import-local\index.js:16:66)
    at C:\Users\lajos\AppData\Roaming\npm\node_modules\webpack-cli\bin\webpack.js:13:6
    at Object.<anonymous> (C:\Users\lajos\AppData\Roaming\npm\node_modules\webpack-cli\bin\webpack.js:514:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\lajos\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:80:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.r

**Comment by yyx990803** [comment]
You have a wrong require for the plugin...

**Comment by martonx** [comment]
Thx!
