### ISSUE TITLE
Cannot use vue-loader with Vue CLI configuration

### ISSUE THREAD

**Issue by neilrichter** [vuejs/vue-loader#1438]
### Version
15.4.0

### Reproduction link
[https://codepen.io/anon/pen/bQKRMp](https://codepen.io/anon/pen/bQKRMp)

### Steps to reproduce
1. I tried to apply style on a v-html element
2. I followed the guide to add configuration to webpack so I can use deep selector `>>>` https://vue-loader.vuejs.org/guide/#vue-cli
3. Trying to rerun the development server
4. Error :

```
$ vue-cli-service serve --open --mode development --port 3000 --dashboard
 INFO  Starting development server...

 ERROR  Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.

Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/Users/neilrichter/repos/nook.sh/node_modules/vue-loader/lib/plugin.js:58:13)
    at webpack (/Users/neilrichter/repos/nook.sh/node_modules/webpack/lib/webpack.js:47:13)
    at serve (/Users/neilrichter/repos/nook.sh/node_modules/@vue/cli-service/lib/commands/serve.js:135:22)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```

### What is expected?
Server runs and I can use `>>>` deep selector 

### What is actually happening?
Server can't run and is throwing an error even if I'm following exactly the official guides to implement the `vue-loader`

**Comment by posva** [comment]
You don't need to add vue-loader to vue-cli, it's already there and deep selector is working out of the box :)
