### ISSUE TITLE
TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by WindTraveler** [vuejs/vue-loader#1440]
### Version
15.4.0

### Reproduction link
[https://github.com/WindTraveler/vue-issue](https://github.com/WindTraveler/vue-issue)

### Steps to reproduce
1. clone the repo code
2. run `npm i`
3. run `npm start` 

### What is expected?
The webpack@4.26.1 could compile the App.vue successfully.

### What is actually happening?
The webpack@4.26.1 failed to compile.
And here is the error info:
```
ERROR in ./src/App.vue?vue&type=template&id=7ba5bd90& (./node_modules/_vue-loader@15.4.2@vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/_vue-loader@15.4.2@vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=template&id=7ba5bd90&)
Module build failed (from ./node_modules/_vue-loader@15.4.2@vue-loader/lib/loaders/templateLoader.js):
TypeError: Cannot read property 'split' of null
    at splitPath (D:\nodejs_work\loader-test\node_modules\_prettier@1.13.7@prettier\third-party.js:5376:25)
    at Object.exports.sync [as findParentDir] (D:\nodejs_work\loader-test\node_modules\_prettier@1.13.7@prettier\third-party.js:5403:20)
    at loadPlugins (D:\nodejs_work\loader-test\node_modules\_prettier@1.13.7@prettier\index.js:26838:36)
    at D:\nodejs_work\loader-test\node_modules\_prettier@1.13.7@prettier\index.js:31220:16
    at Object.format (D:\nodejs_work\loader-test\node_modules\_prettier@1.13.7@prettier\index.js:31241:12)
    at actuallyCompile (D:\nodejs_work\loader-test\node_modules\_@vue_component-compiler-utils@2.3.0@@vue\component-compiler-utils\dist\compileTemplate.js:97:29)
    at compileTemplate (D:\nodejs_work\loader-test\node_modules\_@vue_component-compiler-utils@2.3.0@@vue\component-compiler-utils\dist\compileTemplate.js:29:16)
    at Object.module.exports (D:\nodejs_work\loader-test\node_modules\_vue-loader@15.4.2@vue-loader\lib\loaders\templateLoader.js:42:20)
 @ ./src/App.vue?vue&type=template&id=7ba5bd90& 1:0-233 1:0-233
 @ ./src/App.vue
 @ ./src/index.js
 @ multi ./node_modules/_webpack-dev-server@3.1.10@webpack-dev-server/client?http://localhost:8080 ./src/index.js
```

**Comment by posva** [comment]
You are probably not configuring webpack correctly. I recommend you to use the vue-cli to have an always up-to-date version of the webpack config and extend it if necessary 🙂 
Closing as this is a usage question related to vue-loader and webpack

**Comment by njleonzhang** [comment]
it seems a [bug](https://github.com/prettier/prettier/issues/4637) of lib `prettify`, and still existed in newest version 1.13.7. I workaround the issue by disable prettier with vue-loader [config](https://vue-loader.vuejs.org/options.html#prettify)
