### ISSUE TITLE
Single File Component Cannot add Script Tag

### ISSUE THREAD

**Issue by tun100** [vuejs/vue-loader#1575]
### Version
15.7.1

### Reproduction link
[https://github.com/tun100/issue-vue-loader-failure](https://github.com/tun100/issue-vue-loader-failure)

### Steps to reproduce
1, run `npm i -S -D`
2, run `yarn start`
3, webpack throw a error about vue-loader cannot work well

### What is expected?
run successly without error

### What is actually happening?
display a lots of error infomation, but seems like babel need presets setting. If you remove App.vue import, the bug will disappear. So I guess the bug may be caused by vue-loader or another configuration. Please help me run successly, Thanks you Very Much!

---
ERROR in ./pages/index/App.vue?vue&type=script&lang=js& (./node_modules/_babel-loader@7.1.5@babel-loader/lib?{!./node_modules/_vue-loader@15.7.1@vue-loader/lib??vue-loader-options!./pages/index/App.vue?vue&type=script&lang=js&)
Module build failed (from ./node_modules/_babel-loader@7.1.5@babel-loader/lib/index.js):
ReferenceError: [BABEL] F:\githubProject\workstation\program\frontend\pages\index\App.vue: Unknown option: base.{. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.
    at Logger.error (F:\githubProject\workstation\program\frontend\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (F:\githubProject\workstation\program\frontend\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\file\options\option-manager.js:226:20)
    at OptionManager.init (F:\githubProject\workstation\program\frontend\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (F:\githubProject\workstation\program\frontend\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\file\index.js:212:65)
    at new File (F:\githubProject\workstation\program\frontend\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (F:\githubProject\workstation\program\frontend\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (F:\githubProject\workstation\program\frontend\node_modules\_babel-loader@7.1.5@babel-loader\lib\index.js:50:20)
    at Object.module.exports (F:\githubProject\workstation\program\frontend\node_modules\_babel-loader@7.1.5@babel-loader\lib\index.js:173:20)
 @ ./pages/index/App.vue?vue&type=script&lang=js& 1:0-204 1:220-223 1:225-426 1:225-426
 @ ./pages/index/App.vue
 @ ./pages/index/index.js

**Comment by tun100** [comment]
Already Solve it, because of babelrc file type
