### ISSUE TITLE
Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree

### ISSUE THREAD

**Issue by mhy-web** [vuejs/vue-loader#1672]
```
 error  in ./src/views/pushV2/experiment/detail.vue

Module build failed (from /Users/mhy/node_modules/vue-loader/dist/index.js):
Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/Users/mhy/node_modules/vue-loader/dist/index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadLoader (/Users/mhy/work/ushareit-web-SGPush/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/mhy/work/ushareit-web-SGPush/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/mhy/work/ushareit-web-SGPush/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/mhy/work/ushareit-web-SGPush/node_modules/loader-runner/lib/LoaderRunner.js:185:6
    at context.callback (/Users/mhy/work/ushareit-web-SGPush/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at readFn (/Users/mhy/work/ushareit-web-SGPush/node_modules/cache-loader/dist/index.js:137:7)
    at ReadFileContext.fs.readFile [as callback] (/Users/mhy/work/ushareit-web-SGPush/node_modules/cache-loader/dist/index.js:205:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:320:13)
```

 vue-cli-service: 3.5.3

**Comment by martinsson** [comment]
Had same error. downgrading to v15.9.2 worked for me

**Comment by yyx990803** [comment]
Accidentally published the `next` branch without dist-tag, fixed now.

**Comment by angeldominguezg** [comment]
> Had same error. downgrading to v15.9.2 worked for me

Yes, downgrading the vue-loader to 15.9.2 in the package.json works. Thank's!

**Comment by Omar-Qalei** [comment]
If you have:   `**ERROR  Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.**`
I resolved problem use `**npm install**`

**Comment by juancu8** [comment]
I have the same issue, but when jenkins execute 'npm run lint'. Try downgrading vue-loader from cli and not worked, any suggested?

**Comment by achenwei-chwy** [comment]
using vue-loader @beta.7 still same error. is it still not fixed? downgrade is not an option for me because I am trying to upgrade to webpack5

**Comment by skjnldsv** [comment]
Same here! :)

**Comment by vospascal** [comment]
packageExtensions:
  vue-loader@*:
    peerDependencies:
      '@vue/compiler-sfc': '*'
      webpack: '*'

when your using yarn berry

**Comment by anrananran** [comment]
issue still here ,downgrade to v15 works, but not a good solution

**Comment by Omar-Qalei** [comment]
This error occurred because something doesn't support or incompatible in a configuration in your project between Vue js, Composition API, and Node js.

Example: 
Node js: v12.11.0
```
package.js:
"vue": "^2.6.14",

package-lock.json:
"@vue/composition-api": {
      "version": "1.0.4", <----------- important
      "resolved": "https://registry.npmjs.org/@vue/composition-api/-/composition-api-1.0.4.tgz",
      "integrity": "sha512-3OzvW8RS7/7kxE+SDXm8zSLZRy9GtCYwyLYdnGtIsqXRSt5nWkA7zu80Cw8Vg+67jglrpMdVBBy7AUXAB34ZSw==",
      "requires": {
        "tslib": "^2.3.0"
      }
    },
```
