### ISSUE TITLE
New Beta of Vue 3 Error with VuetifyJS

### ISSUE THREAD

**Issue by sinner** [vuejs/vue-loader#1675]
### Version
4.3.1

### Reproduction link
[https://github.com/sinner/vue3-new-features/tree/error/vue-3-plugin](https://github.com/sinner/vue3-new-features/tree/error/vue-3-plugin)

### Environment info
```
- MacOS
- Node v13.7.0
- @vue/cli: 4.3.1
- vuetify: 2.2.28
- vuetify-loader: 1.4.3
```

### Steps to reproduce
Add the vue-next plugin in an existing Vue CLI project already using VuetifyJS and execute `npm run serve`

### What is expected?
After adding the vue-next plugin executing `npm run serve` it should serve the application with the Vue 3 new features without errors

### What is actually happening?
After executing `npm run serve` it throws an error

---
I've reviewed previously this ticket https://github.com/vuetifyjs/vuetify-loader/pull/97 and I've seen in the vuetify-loader the lines with the fixes even with some improvements, but the error is still there:

These are the error details:
```sh
> npm run serve
> vue3-features-backp@0.1.0 serve /Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/vuetify-loader/lib/plugin.js:29:13)
    at webpack (/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/@vue/cli-service/lib/commands/serve.js:162:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue3-features-backp@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue3-features-backp@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jsinner/.npm/_logs/2020-05-14T15_12_21_989Z-debug.log

<!-- generated by vue-issues. DO NOT REMOVE -->
```

**Comment by yyx990803** [comment]
Vuetify does not support Vue 3 yet AFAIK.
