### ISSUE TITLE
Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.

### ISSUE THREAD

**Issue by RabbitRab6it** [vuejs/vue-loader#1715]
**error at start**

 ERROR  Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.
Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (D:\code\links-cloud\linkyun_frontend_pc\node_modules\@vue\cli-service\node_modules\vue-loader\dist\index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
at D:\code\links-cloud\linkyun_frontend_pc\node_modules\@vue\cli-service\lib\config\base.js:110:16     
    at D:\code\links-cloud\linkyun_frontend_pc\node_modules\@vue\cli-service\lib\Service.js:236:40
    at Array.forEach (<anonymous>)

@vue/cli-service --version  => ^4.3.1

**Comment by RabbitRab6it** [comment]
try 'npm add vue-loader@15.9.2 ', the above error still occurs.

**Comment by vospascal** [comment]
packageExtensions:
  vue-loader@*:
    peerDependencies:
      '@vue/compiler-sfc': '*'
      webpack: '*'

when your using yarn berry
