### ISSUE TITLE
Vue3.0自定义loader加载md文件的时候报错了

### ISSUE THREAD

**Issue by bestqc** [vuejs/vue-loader#1739]
### Version
15.9.3

### Reproduction link
[https://github.com/bestqc/vue3-loader-error-demo](https://github.com/bestqc/vue3-loader-error-demo)

### Steps to reproduce
使用vue 3.0.0版本自定义loader加载文件。在web.config.js中配置对应的.md文件处理。运行报错，同样的代码，在2.6版本上是正确的，。查看了文档也没找到错误在哪儿，搜索引擎上的解决方案是保持vue-template-compiler和vue的版本一致，但是vue-template-compiler最新版本才2.6.12，无法保持一致，所以这个问题一直无法解决

### What is expected?
需要正确加载loader处理自定义文件

### What is actually happening?
报错了，错误信息
``` javascript
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (C:\Users\cx\Desktop\bao\demo3\node_modules\@vue\component-compiler-utils\dist\parse.js:14:23)
    at Object.module.exports (C:\Users\cx\Desktop\bao\demo3\node_modules\vue-loader\lib\index.js:67:22)
```

**Comment by bestqc** [comment]
升级到预览版的vue-loader就正常了。
