### ISSUE TITLE
Cannot read Property ‘parseComponent’ of undefined

### ISSUE THREAD

**Issue by webMing** [vuejs/vue-loader#1741]
#### error message
```
ERROR in ./src/vue/App.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):

Vue packages version mismatch:

- vue@3.0.0 (/Users/stephanie/Desktop/webpack/node_modules/vue/index.js)
- vue-template-compiler@2.6.12 (/Users/stephanie/Desktop/webpack/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
 @ ./src/main.js 7:0-32 10:7-10

ERROR in ./src/vue/App.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/stephanie/Desktop/webpack/node_modules/@vue/component-compiler-utils/dist/parse.js:15:23)
    at Object.module.exports (/Users/stephanie/Desktop/webpack/node_modules/vue-loader/lib/index.js:67:22)
 @ ./src/main.js 7:0-32 10:7-10

webpack 5.1.0 compiled with 2 errors in 4436 ms


```

#### package.json  
```
    "vue-loader": "^15.9.3",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^5.1.0",
    "vue"":"^3.0.0"
```

#### webpack.config.js
```
 const VueLoaderPlugin = require('vue-loader/lib/plugin')
 module:{
           rules:
               { 
              
                   test: /\.vue$/,
                   loader: 'vue-loader'
                },
        },
  
  
 plugins: [
            new VueLoaderPlugin()
  ],
```

I have  update the component 'vue-template-Compiler' to match the vue version.However, the version of the compiler was up to 2.6.12, while the vue version was 3.0.0, not  resolve this problem

**Comment by Vac1911** [comment]
I know this thread is closed but I wanted to share my solution for other people who stumble across this with google.

Using `"vue-loader": "^16.0.0-rc.1"` seems to make everything run fine. While I don't think this has any effect, I am using encore-webpack.

**Comment by habc0807** [comment]
I resolved the issue.

```
npm uninstall @vue/component-compiler-utils
npm install --dev @vue/component-compiler-utils@3.1.2
```

**Comment by LucianoAngel** [comment]
> I resolved the issue.
> 
> ```
> npm uninstall @vue/component-compiler-utils
> npm install --dev @vue/component-compiler-utils@3.1.2
> ```

@habc0807 
did you have installed `vue-template-compiler@2.6.12` ?

**Comment by mryellow** [comment]
>  (your robot friend!).

@vue-bot You are no friend.

**Comment by luc-constantin** [comment]
I know this is closed but hopefully you'll solve it by runnin this command: npm update vue-template-compiler

I worked for me.

**Comment by JosephBerm** [comment]
> I worked for me.

I did this and the package version remained the same but it still worked for me, thank you!
