### ISSUE TITLE
编译失败, 报错 TypeError: Cannot read property 'content' of null

### ISSUE THREAD

**Issue by idrunk** [vuejs/vue-loader#1747]
### Version
16.0.0-beta.8

### Reproduction link
[https://github.com/idrunk/vue-loader-bug-reproduction](https://github.com/idrunk/vue-loader-bug-reproduction)

### Steps to reproduce
- 配置webpack的cache.type为filesystem, 开启缓存
- 初始化一个Vue3 Typescript的项目, 建立一个根单文件组件并使用ts版setup语法糖, 建立一个子单文件组件并使用ts版setup语法糖, 在根组件中导入子组件
- 第一次编译, 正常通过能运行
- 后续编译, 编译失败, 报下述错误
```
TypeError: Cannot read property 'content' of null
    at Object.selectBlock (D:\Temp\vue3\1\node_modules\vue-loader\dist\select.js:25:45)
    at Object.loader (D:\Temp\vue3\1\node_modules\vue-loader\dist\index.js:60:25)
```

### What is expected?
编译通过

### What is actually happening?
编译失败

---
经过跟踪排查, 发现在前行插入下述代码, 多次编译都能正常通过, 但我感觉这不是解决之道
``` js
        if (incomingQuery.type === 'script' && !descriptor.scriptCompiled && descriptor.scriptSetup) {
            descriptor.scriptCompiled = compiler_sfc_1.compileScript(descriptor, {
                babelParserPlugins: options.babelParserPlugins,
            })
        }
```

**Comment by bmunoz89** [comment]
I'm having the same issue when is used the command `yarn build`

https://github.com/bmunoz89/vue3-playground/

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                              10:09:59 PM

 error  in ./src/views/Experimental.vue?vue&type=script&lang=ts&setup=true

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'content' of null
    at PoolWorker.fromErrorObj (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at /Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:152:14
    at Object.selectBlock (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/vue-loader-v16/dist/select.js:25:45)
    at Object.loader (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/vue-loader-v16/dist/index.js:59:25)

 @ ./src/views/Experimental.vue?vue&type=script&lang=ts&setup=true 1:0-388 1:0-388 1:389-766 1:389-766
 @ ./src/views/Experimental.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 ERROR  Build failed with errors.
```

**Comment by idrunk** [comment]
> I'm having the same issue when using the `yarn build` command
> 
> https://github.com/bmunoz89/vue3-playground/
> 
> ```
>  ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                              10:09:59 PM
> 
>  error  in ./src/views/Experimental.vue?vue&type=script&lang=ts&setup=true
> 
> Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
> Thread Loader (Worker 0)
> Cannot read property 'content' of null
>     at PoolWorker.fromErrorObj (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:262:12)
>     at /Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:204:29
>     at mapSeries (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/neo-async/async.js:3625:14)
>     at PoolWorker.onWorkerMessage (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:170:35)
>     at /Users/BorisM/Documents/Vue3/vue3-playground/node_modules/thread-loader/dist/WorkerPool.js:152:14
>     at Object.selectBlock (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/vue-loader-v16/dist/select.js:25:45)
>     at Object.loader (/Users/BorisM/Documents/Vue3/vue3-playground/node_modules/vue-loader-v16/dist/index.js:59:25)
> 
>  @ ./src/views/Experimental.vue?vue&type=script&lang=ts&setup=true 1:0-388 1:0-388 1:389-766 1:389-766
>  @ ./src/views/Experimental.vue
>  @ ./src/router/index.ts
>  @ ./src/main.ts
>  @ multi ./src/main.ts
> 
>  ERROR  Build failed with errors.
> ```

My issue was trigger by the 'cache' option in webpack's config, I saw your project not with webpack, Maybe our issue are different.

**Comment by bmunoz89** [comment]
@idrunk I make another branch to remove the experimental feature `<script setup>`, which is the same feature that you are using, and in that [branch](https://github.com/bmunoz89/vue3-playground/tree/it-works) works without throwing that error.

**Comment by yoyoys** [comment]
confirmed same error at `vue-cli, `setup` feature is only support serve mode, not build time.

**Comment by FairyEver** [comment]
> confirmed same error at `vue-cli`, `setup` feature is only support serve mode, not build time.

I also have this problem, without typescript

**Comment by bowencool** [comment]
我什么都没干，重试就好了...薛定谔的错误

**Comment by sodatea** [comment]
As said in the release note:

> - `<script setup>` support is experimental. It does not work well with `thread-loader`. In Vue CLI, you need to set [`parallel: false`](https://cli.vuejs.org/config/#parallel) for this feature to work correctly.

**Comment by bodograumann** [comment]
After setting `parallel: false` in the `vue.config.js` I also had to `rm node_modules/.cache -rf` before building worked again.

**Comment by frxing** [comment]
This API syntax can only be used after Vue 3.0.3

**Comment by cary-hu** [comment]
Still meet this problem when enable filesystem cache, The error is the property "id" is missing when re-build after file changed. Any idea?
