### ISSUE TITLE
_vm._ssrEscape is not a function error during single component testing using mocha and @vue/testing-utils

### ISSUE THREAD

**Issue by mfissehaye** [vuejs/vue-loader#1810]
### Version
15.9.2

### Reproduction link
[https://github.com/mfissehaye/laravel-vue-testing/tree/master/resources/js](https://github.com/mfissehaye/laravel-vue-testing/tree/master/resources/js)

### Steps to reproduce
I am testing a single component using @vue/test-utils version ^1.1.3
vue ^2.5.17
vue-loader 15.9.2
vue-template-compiler 2.6.12

Here is the component Dashboard.vue

```
<template>
    <nav>
        <span class="count" v-text="count"></span>
        <button @click="count  ">Increment</button>
    </nav>
</template>

<script>
export default {
    data() {
        return {
            count: 0
        }
    }
}
</script>
```

And here is the testing code Dashboard.spec.js

```
import { mount } from '@vue/test-utils'
import Dashboard from '../components/Dashboard.vue';
import expect from 'expect'

describe('Dashboard', () => {
    let wrapper
    beforeEach(() => {
        wrapper = mount(Dashboard)
    })

    it('defaults to count of 0', () => {
        expect(wrapper.vm.count).toBe(0)
    })

    it('increments the count when the button is clicked', () => {
        expect(wrapper.vm.count).toBe(0)

        wrapper.find('button').trigger('click')
        
        expect(wrapper.vm.count).toBe(1)
    })

    it('presents the current count', async () => {
        expect(wrapper.find('.count').html()).toContain(0)
        
        wrapper.find('button').trigger('click')

        await wrapper.vm.$nextTick()

        expect(wrapper.find('.count').html()).toContain(1)
    })
})
```

Now when I run yarn test (which is the same as `mochapack --mode development --webpack-config webpack.config.js --require resources/js/tests/setup.js resources/js/tests/**/*.spec.js`) I get the following error.

```
1) Dashboard
       "before each" hook for "defaults to count of 0":
     TypeError: _vm._ssrEscape is not a function
      at Proxy.render (webpack:///./resources/js/components/Dashboard.vue?./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options:11:13)
      at VueComponent.Vue._render (node_modules\vue\dist\vue.runtime.common.dev.js:3538:22)
      at VueComponent.updateComponent (node_modules\vue\dist\vue.runtime.common.dev.js:4054:21)
      at Watcher.get (node_modules\vue\dist\vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules\vue\dist\vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules\vue\dist\vue.runtime.common.dev.js:4061:3)
      at VueComponent.Vue.$mount (node_modules\vue\dist\vue.runtime.common.dev.js:8392:10)
      at init (node_modules\vue\dist\vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules\vue\dist\vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules\vue\dist\vue.runtime.common.dev.js:5905:9)
      at VueComponent.patch [as __patch__] (node_modules\vue\dist\vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules\vue\dist\vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules\vue\dist\vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules\vue\dist\vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules\vue\dist\vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules\vue\dist\vue.runtime.common.dev.js:4061:3)
```

### What is expected?
I can temporarily fix this by enclosing the template component in `<no-ssr>` but I want the test to pass without it.

### What is actually happening?
The test is failing instead.

**Comment by mfissehaye** [comment]
I simply added an option to the loader in my `webpack.config.js` file and everything works fine now. Here is my modified webpack.config.js. I added the `optimizeSSR` part along with `options`

```
const { VueLoaderPlugin } = require('vue-loader')

module.exports = {
    target: 'node',
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    optimizeSSR: false
                }
            },
            {
                test: /\.scss$/,
                use: [
                  'vue-style-loader',
                  'css-loader',
                  'sass-loader'
                ]
              }
        ]
    },

    plugins: [
        new VueLoaderPlugin()
    ]
}
```
