### ISSUE TITLE
<option> element is optional closing tag, but vue-loader flags it as an error

### ISSUE THREAD

**Issue by wdporter** [vuejs/vue-loader#1830]
### Version
16.1.2

### Reproduction link
[https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbiAgPHNlbGVjdD5cblx0XHRcdDxvcHRpb24gdmFsdWU9MjAyMT4yMDIxXG5cdFx0XHQ8b3B0aW9uIHZhbHVlPTIwMjA MjAyMFxuXHRcdFx0PG9wdGlvbiB2YWx1ZT0yMDIwPjIwMTlcblx0XHQ8L3NlbGVjdD5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ In0=](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE e3sgbXNnIH19PC9oMT5cbiAgPHNlbGVjdD5cblx0XHRcdDxvcHRpb24gdmFsdWU9MjAyMT4yMDIxXG5cdFx0XHQ8b3B0aW9uIHZhbHVlPTIwMjA MjAyMFxuXHRcdFx0PG9wdGlvbiB2YWx1ZT0yMDIwPjIwMTlcblx0XHQ8L3NlbGVjdD5cbjwvdGVtcGxhdGU XG5cbjxzY3JpcHQgc2V0dXA XG5jb25zdCBtc2cgPSAnSGVsbG8gV29ybGQhJ1xuPC9zY3JpcHQ In0=)

### Steps to reproduce
I created a bog standard vue cli

Then I added to App.vue, inside the template element,  
    < select >< option value=2021 > < /select >

### What is expected?
I expect to not flag this as an error. There is no error, closing tags are allowed to be omitted for "option" and a bunch of other elements also e.g. p, li etc. 

The message says "is missing an end tag". 

Acutually, no. Nothing is missing an end tag, in this case, we have an option element and end tags are not required as per html spec. 

I understand that you might consider this bad practice, or ugly to look at or "what every one else does". But it's really a matter of what is legally allowed in the html spec. https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission  

The spec doesn't require it, There is no browser in existence that has ever required it, so why do you?

You are treating this as if we have an xhtml doctype!.

NB I think this is for vue-loader, because that's what the error message says, but I'm not sure really. 

Or: I might expect a different error message, such as, "vue-loader  requires end tags, sorry."

### What is actually happening?
Failed to compile.

    ./src/App.vue
    Module Error (from ./node_modules/vue-loader-v16/dist/index.js):
    VueCompilerError: 
    VueCompilerError: Element is missing end tag.
    at C:\Temp\imfl\src\App.vue:17:4
    15 |    <header>
    16 |      <select>
    17 |  			<option value=2021>2021
       |     ^
    18 |  		</select>
    19 |    </header>
    at C:\Temp\imfl\src\App.vue:17:4 
    15 |    <header>
    16 |      <select>
    17 |  			<option value=2021>2021
       |     ^
    18 |  		</select>
    19 |    </header>

**Comment by sodatea** [comment]
Is there anywhere in the documentation that says that Vue template in an single file component is fully HTML spec compliant?

If so, that documentation should be fixed.
