### ISSUE TITLE
Vue 3 hot reload fails using vue-loader 16.8.2

### ISSUE THREAD

**Issue by bgowers** [vuejs/vue-loader#1907]
### Version
16.8.2

### Reproduction link
[vue hot reload bug repository](https://github.com/bgowers/vue-hotreload-bug)

### Steps to reproduce
1. Clone linked repo
2. CD into root
3. npm install
4. npm run dev
5. Make a minor change in src/components/variants/Empty/index.vue or script.ts (delete and re-add a character)
6. Save the file
7. See hot reload fail

### What is expected?
On save, hot reload the application successfully.

### What is actually happening?
A webpack error: 

```
<e> [webpack-dev-middleware] Error: The loaded module contains errors
<e>     at /Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/dependencies/LoaderPlugin.js:108:11
<e>     at /Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/Compilation.js:1854:5
<e>     at /Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/util/AsyncQueue.js:352:5
<e>     at Hook.eval [as callAsync] (eval at create (/Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
<e>     at AsyncQueue._handleResult (/Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/util/AsyncQueue.js:322:21)
<e>     at /Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/util/AsyncQueue.js:305:11
<e>     at /Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/Compilation.js:1384:15
<e>     at /Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/HookWebpackError.js:68:3
<e>     at Hook.eval [as callAsync] (eval at create (/Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
<e>     at Cache.store (/Users/benjamingowers/Dev/vue-hotreload-bug/node_modules/webpack/lib/Cache.js:107:20)
```

**Comment by bgowers** [comment]
Also occurs on 16.8.3

**Comment by freszb** [comment]
It should work with 16.8.1.

**Comment by Enoooch** [comment]
> It should work with 16.8.1.

Locked in ```vue-loader@16.8.1```, still a no go.


#### Related issue
[Blank screen with hot reloading](https://github.com/vuejs/vue-next/issues/4654)


#### Versions:
```
vue@3.2.24
@vue/compiler-sfc@3.2.24
vue-cli@4.5.0
```

**Comment by nolimitdev** [comment]
In my VueJS project HMR correctly works with 16.8.1, 16.8.2, 16.8.3 and latest 17.0.0 - all just tested.

**Comment by lmsfelipe** [comment]
After migrating v2 to v3 I started to have a similar issue, the console prints `re-render` and `reload` but nothing is reflected in the page. 
vue-loader version 16.8.3

**Comment by uojo** [comment]
> After migrating v2 to v3 I started to have a similar issue, the console prints `re-render` and `reload` but nothing is reflected in the page. I've tried to lock the version to 16.8.1, but it also doesn't work.

me too
