### ISSUE TITLE
Cannot read properties of undefined (reading 'NormalModule')

### ISSUE THREAD

**Issue by albizeka** [vuejs/vue-loader#1969]
### Version
16.8.3

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eNo9j71uwzAMhF+F5eIWqCV0NZQA3foGXbikjpw40B9EOR0EvXspp8imu9N9OFb8TEndN4sTGp7zmgqwLVs6Ulh9irlAhWwXaLDk6GGQrwMFCnMMXMDzBQ49fx2+rHMRvmN255fhjYLRD5yARBTrkzsVKwrAXD+Ote7l1owWtbtrSFuB++jj2boDoeSEEhn9bOM7PlaN/pTUjWOQ3bW36T9gwgl2p3uytmvCaymJJ615mfu1N1YxX7S8VN5CWb1Vlv34k+Mv2yxgwo5oFBq2P3/sZE8=)

### Steps to reproduce
I updated the vue 3 to vue 3 typescript and this is happened

### What is expected?
I'm expecting a support from community that might faced this issue and fixed it, since I'm trying to fix it for hours now.

### What is actually happening?
I'm updating the vue 3 project to vue 3 typescript and this is the error i'm encountering:

 ERROR  TypeError: Cannot read properties of undefined (reading 'NormalModule')
TypeError: Cannot read properties of undefined (reading 'NormalModule')
    at VueLoaderPlugin.apply (/Users/albizeka/Desktop/project/resources/client/node_modules/vue-cli-plugin-vue-next/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
    at webpack (/Users/albizeka/Desktop/project/resources/client/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Users/albizeka/Desktop/project/resources/client/node_modules/@vue/cli-service/lib/commands/serve.js:137:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I read some of things that i found on another pages, like to downgrade the webpack and ts-loader to 8.2.0 but none of this seemed to work.

**Comment by Abdulhai-Mohamed** [comment]
still face the same problem
TypeError: Cannot read properties of undefined (reading 'NormalModule')
