### ISSUE TITLE
Error when webpacking .vue file

### ISSUE THREAD

**Issue by he-yang** [vuejs/vue-loader#1978]
Here is the error I get when I try to webpack

```
Compiled with problems:X

ERROR in ./vue/index.vue

Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (D:\FDT\node_modules\vue-loader\dist\index.js:70:34)

```

Below is the content in my index.vue file
```
<template>
  <div class="example">{{ msg }}</div>
</template>

<script>
export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>

<style>
.example {
  color: red;
}
</style>
```

Any idea how to solve this?

**Comment by netandreus** [comment]
I have the same issue. Is there any solution?

**Comment by he-yang** [comment]
> I have the same issue. Is there any solution?

I got reply from here https://github.com/vuejs/vue-loader/issues/1973#issuecomment-1183982271

basically, you need to downgrade vue-load to @15, if you are using vue2.0

**Comment by netandreus** [comment]
It does not helps me. I've got an error:
```
   ERROR in ../ts/Vue/TestComponent.vue
    Module build failed (from /var/www/project/current/node_modules/vue-loader/dist/index.js):
    TypeError: Cannot read property 'styles' of undefined
        at Object.loader (/var/www/project/current/node_modules/vue-loader/dist/index.js:70:34)
     @ ../ts/Vue/VueApp.ts 7:42-72

    ERROR in [at-loader] ./src/Resources/public/ts/Vue/VueApp.ts:2:27
        TS2307: Cannot find module './TestComponent.vue'.
```

My webpack versions are:
```
"dependencies": {
    "@ag-grid-community/all-modules": "^22.0.0",
    "@ag-grid-community/react": "^22.0.0",
    "@ckeditor/ckeditor5-build-classic": "^27.0.0",
    "@ckeditor/ckeditor5-upload": "^29.2.0",
    "@types/bootstrap": "4.3.1",
    "@types/jquery": "^3.3.1",
    "@types/lodash.memoize": "^4.1.6",
    "@types/moment": "^2.13.0",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.9.0",
    "@types/react-router-dom": "^4.3.5",
    "@types/select2": "^4.0.47",
    "@types/simplebar": "^2.4.2",
    "@types/url-parse": "^1.1.0",
    "@types/js-cookie": "^3.0.0",
    "autoprefixer": "^9.1.3",
    "awesome-typescript-loader": "^5.2.1",
    "bootstrap": "4.3.1",
    "bootstrap-daterangepicker": "^2.1.25",
    "chart.js": "^2.9",
    "clipboard": "2.0.0",
    "css-loader": "1.0.0",
    "detect-mobile-browser": "https://github.com/vrebierr/detect-mobile-browser.git#0.0.1",
    "dropify": "^0.2.2",
    "exports-loader": "^0.7.0",
    "expose-loader": "^0.7.5",
    "file-loader": "^2.0.0",
    "floatthead": "2.1.1",
    "flow-bin": "^0.107.0",
    "font-awesome": "^4.7.0",
    "freeotp": "https://github.com/freeotp/freeotp.github.io.git",
    "freeotp.github.io": "https://github.com/freeotp/freeotp.github.io.git",
    "fullcalendar": "3.9.0",
    "i18next": "^19.0.0",
    "i18next-loader": "^0.0.6",
    "ignore-loader": "^0.1.2",
    "immutable": "^3.8.2",
    "inputmask": "robinherbots/inputmask",
    "intl-polyfill": "^0.0.3",
    "intl-tel-input": "^17.0.0",
    "jquery": "3.3.1",
    "json-loader": "^0.5.7",
    "jstree": "^3.3.7",
    "jstreegrid": "^3.9.0",
    "loader-utils": "^1.1.0",
    "lodash.memoize": "^4.1.2",
    "mini-css-extract-plugin": "^0.4.3",
    "mobile-detect": "^1.4.3",
    "moment": "^2.18.1",
    "node-sass": "^4.5.3",
    "number_format-php": "^1.0.9",
    "pdfjs-dist": "^2.5.207",
    "postcss-loader": "^3.0.0",
    "postcss-move-props-to-bg-image-query": "^0.2.5",
    "promise-polyfill": "^8.1.0",
    "qrcode-generator": "^1.4.3",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-router-dom": "^5.0.1",
    "resolve-url-loader": "^3.0.0",
    "sass-loader": "7.1.0",
    "select2": "^4.0.13",
    "simplebar": "4.2.1",
    "simplebar-react": "1.2.1",
    "source-map-loader": "^0.2.4",
    "style-loader": "^0.21.0",
    "svg-inline-loader": "^0.8.0",
    "svg-transform-loader": "^2.0.0",
    "svg-url-loader": "^2.3.2",
    "toastr": "2.1.4",
    "typescript": "^3.1.1",
    "url-loader": "1.0.0",
    "url-parse": "^1.4.1",
    "webfonts-generator": "^0.4.0",
    "webpack": "4.17.1",
    "webpack-cli": "3.1.0",
    "x-editable": "^1.5.1",
    "yaml-loader": "^0.5.0",
    "js-cookie": "^3.0.0",
    "cyrillic-to-translit-js": "3.1.0",
    "vue": "^2.6.14",
    "vue-loader": "^15.10.0"
  },
```

VueApp.js
```
import Vue from "vue";
import TestComponent from "./TestComponent.vue";

var vueApp = new Vue({
    el: '#vue-app',
    name: 'VueApp',
    components: {
        TestComponent: TestComponent
    },
});
```

TestComponent.vue
```
<template>
  TTTTTT
</template>

<script>
export default {
  name: "TestComponent"
}
</script>

<style scoped>

</style>
```

Do you have any ideas, what's the problem?
