### ISSUE TITLE
TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by shrikaushik** [vuejs/vue-loader#2066]
TypeError: Cannot read property 'compilation' of undefined
    at VueLoaderPlugin.apply (C:\myapp\node_modules\vue-loader\dist\pluginWebpack4.js:10:24)
    at Compiler.apply (C:\myapp\node_modules\webpack\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\myapp\node_modules\webpack\lib\webpack.js:33:19)
    at startDevServer (C:\myapp\node_modules\webpack-dev-server\bin\webpack-dev-server.js:367:16)
    at processOptions (C:\myapp\node_modules\webpack-dev-server\bin\webpack-dev-server.js:350:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

package.json: 

```
"dependencies": {
    "vue": "^3.1.0",
    "@vue/compat": "^3.1.0",
},
"devDependencies": {
    "@vue/compiler-sfc": "^3.1.0",
    "vue-loader": "^16.0.0",
    "vue-style-loader": "^3.0.1",
    "webpack": "^3.12.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
}
```

**Comment by shrikaushik** [comment]
resolved after webpack upgrade.
