### ISSUE TITLE
vue-loader 配置问题

### ISSUE THREAD

**Issue by icepy** [vuejs/vue-loader#283]
Hi 我使用了vue-loader来处理.vue文件，但是webpack构建时报错了。

报错信息：

```
ERROR in ./app/src/components/header/index.vue
Module parse failed: /Users/xiangwenwen/mulgore/weekly-background/public/app/src/components/header/index.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseStatement (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:1771:23)
    at Parser.pp.parseTopLevel (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/xiangwenwen/mulgore/weekly-background/public/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 @ ./app/src/interface/default/index.js 19:15-59
```

**webpack 配置文件**

```JavaScript
var path = require('path');
var webpack = require('webpack');
var ROOTPATH = path.resolve('.');
var plugins = [];

var config = {
  entry: {
    app: './app/src/index.js',
    commod: ['vue','vue-router']
  },
  output: {
    path: path.resolve(ROOTPATH,'bundle/'),
    filename: '[name].js'
  },
  module:{
    loaders:[
      {
        test: /.\vue$/,
        loader: 'vue-loader',
        exclude: /(node_modules)/
      },
      {
        test: /.\js$/,
        loader: 'babel-loader',
        exclude: /(node_modules)/
      },
      {
        test: /.\less$/,
        loader: 'less-loader',
        exclude: /(node_modules)/
      }
    ]
  },
  devtool: 'source-map',
  extensions: ['', '.js', '.css','.vue','.less', '.png', '.jpg']
};

module.exports = config;

```

**.vue** 文件：

```vue
<template>
  <div class="header" id="header">
    {{ msg }}
  </div>
</template>

<script>
  import Vue from 'vue';
  const HeaderNav = {
    data (){
      return {
        msg: 'Hello World'
      }
    }
  }
  export default HeaderNav;
</script>

<style lang="less">

</style>

```

vue-loader我也是安装成功了的，看起来告诉我是有一个语法错误，实在是看不出来。

**Comment by WellerQu** [comment]
@icepy Hi, I have the same problem, Could u help me to resolve it ?

**Comment by shaoqiming** [comment]
请问你这个问题解决了吗？我也遇到看这个问题，能请教一下解决方法吗？
