### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by lessYFF** [vuejs/vue-loader#343]
ERROR in ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/footer.vue
Module build failed: Error: Parse Error:
`<footer id='footer' class='fix-footer'>
    <ul class='nav-bottom'>
      <li><a class='home v-link-active' v-link={'name':'home'} >首页</a></li>
      <li><a class='find' v-link={'name':'find'}>发现</a></li>
      <li><a class='service' v-link={'name':'service'}>客服</a></li>
      <li><a class='personal' v-link={'name':'personal'}>我的</a></li>
    </ul>
  </footer>`
    at new HTMLParser (C:\Users\Administrator\Desktop\webpack-yyl\node_modules\html-minifier\src\htmlparser.js:236:13)
    at minify (C:\Users\Administrator\Desktop\webpack-yyl\node_modules\html-minifier\src\htmlminifier.js:945:3)
    at Object.exports.minify (C:\Users\Administrator\Desktop\webpack-yyl\node_modules\html-minifier\src\htmlminifier.js:1294:10)
    at Object.module.exports (C:\Users\Administrator\Desktop\webpack-yyl\node_modules\vue-html-loader\index.js:85:26)
 @ ./src/components/footer.vue 3:19-130

**Comment by jbruni** [comment]
I'm not sure if this syntax is supported: ` v-link={'name':'home'}`

I believe you should wrap attribute contents with quotes, like this: `v-link="{'name':'home'}"`

**Comment by LinusBorg** [comment]
Closing for inactivity.
