### ISSUE TITLE
[Suggestion] Warn on empty bindings when compiling

### ISSUE THREAD

**Issue by Async0x42** [vuejs/vue-loader#351]
From: https://github.com/vuejs/vue/issues/3671

I think that when binding a prop, if we forget to enter anything (i.e :col-key=""), then a warning should be displayed when compiling. (single file components).

Right now it gives a fairly non-descript exception being thrown (the line number doesn't point to where the root problem was)

 ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-38!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/charts/OverallViewSingleStat.vue Module build failed: SyntaxError: Unexpected token (63:17) at Parser.pp$3.parseExprSubscripts (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1749:23) at Parser.pp$3.parseMaybeUnary (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1726:21) at Parser.pp$3.parseExprOps (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1671:23) at Parser.pp$3.parseMaybeConditional (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1654:23) at Parser.pp$3.parseMaybeAssign (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1631:23) at Parser.pp$3.parsePropertyValue (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:2032:91) at Parser.parseObj (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:3919:16) at Parser.pp$3.parseExprAtom (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1839:21) at Parser.parseExprAtom (P:\Wor\node_modules\vue-template-es2015-compiler\buble.js:3824:26) at Parser.pp$3.parseExprSubscripts (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1749:23) at Parser.pp$3.parseMaybeUnary (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1726:21) at Parser.pp$3.parseExprOps (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1671:23) @ ./src/components/charts/OverallViewSingleStat.vue 7:23-155

**Comment by LinusBorg** [comment]
Hello Async0x42,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by yyx990803** [comment]
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.
