### ISSUE TITLE
@media goes wrong when lang="stylus"

### ISSUE THREAD

**Issue by ablipan** [vuejs/vue-loader#50]
If change this example's [b.vue's](https://github.com/vuejs/vue-loader-example/blob/master/src/components/b.vue) style content to:
```html
<style lang="stylus" scoped>
.container
  border: 1px solid #f00
h2
  color: #393;
@media print
  .foo
    color: #000
</style>
```
and run the ```npm run build```
will get the error below:
```javascript
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/b.vue
Module build failed: TypeError: Cannot read property 'valueOf' of undefined
    at tokenize (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss-selector-parser/dist/tokenize.js:34:24)
    at new Parser (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss-selector-parser/dist/parser.js:89:49)
    at Processor.process (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss-selector-parser/dist/processor.js:36:25)
    at /Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/lib/style-rewriter.js:15:10
    at Root.each (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/container.js:89:22)
    at /Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/lib/style-rewriter.js:8:10
    at LazyResult.run (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:197:24)
    at /Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:110:37
    at LazyResult.asyncTick (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:124:15)
    at processing.Promise.then._this2.processed (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:150:20)
    at LazyResult.async (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:147:27)
    at LazyResult.then (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:72:21)
    at Object.module.exports (/Users/Pan/Documents/Js/js framework/Vue/vue-loader-example/node_modules/vue-loader/lib/style-rewriter.js:26:6)
 @ ./~/style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/b.vue 4:14-240
```
Is this a bug or my bad?

**Comment by yyx990803** [comment]
This is actually a bug in scoped style rewriting. Fixed in latest commit, will be out in 6.0.2.
