### ISSUE TITLE
Can't load .vue after update babel to 6.0.0

### ISSUE THREAD

**Issue by g0ne150** [vuejs/vue-loader#54]
ERROR in ./~/babel-loader?optional[]=runtime&loose=all&nonStandard=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/js/components/header/header.vue
Module build failed: ReferenceError: [BABEL] /Users/gaozepan/Documents/youmeiba/node_modules/vue-loader/lib/selector.js?type=script&index=0!/Users/gaozepan/Documents/youmeiba/src/js/components/header/header.vue: Unknown option: base.optional
    at Logger.error (/Users/gaozepan/Documents/youmeiba/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/Users/gaozepan/Documents/youmeiba/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
    at OptionManager.init (/Users/gaozepan/Documents/youmeiba/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:10)
    at File.initOptions (/Users/gaozepan/Documents/youmeiba/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/gaozepan/Documents/youmeiba/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/gaozepan/Documents/youmeiba/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/gaozepan/Documents/youmeiba/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/gaozepan/Documents/youmeiba/node_modules/babel-loader/index.js:69:12)
 @ ./src/js/components/header/header.vue 2:17-169

//package.json
{
  "version": "1.0.0",
  "main": "webpack.config.js",
  "dependencies": {
    "babel-loader": "^6.0.0",
    "babel-runtime": "^6.0.14",
    "css-loader": "^0.21.0",
    "extract-text-webpack-plugin": "^0.8.2",
    "file-loader": "^0.8.4",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.6",
    "underscore": "^1.8.3",
    "vue": "^1.0.3",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^6.0.1",
    "webpack": "^1.12.2",
    "vue-validator": "^1.4.4",
    "vue-hot-reload-api": "^1.2.1"
  },
  "devDependencies": {
    "babel-core": "^6.0.14",
    "babel-loader": "^6.0.0",
    "babel-preset-es2015": "^6.0.14"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by yyx990803** [comment]
Babel 6.0 is a breaking release. `vue-loader` doesn't work with the new api yet.

**Comment by g0ne150** [comment]
Thanks!
