### ISSUE TITLE
doc error: sugarcss is not defined

### ISSUE THREAD

**Issue by chovy** [vuejs/vue-loader#553]
https://github.com/vuejs/vue-loader/blob/master/docs/en/features/postcss.md

the example here for sugarcss is wrong or at least incomplete.

I tried this:

```
vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: {
      plugins: [
        require('postcss-cssnext')(),
        require('autoprefixer')({
          browsers: ['last 2 versions']
        })
      ],
      options: {
        parser: require('sugarcss')
      }
    }
  }

```

but I get a syntax error:

$ npm run dev

```
/Users/user/project/node_modules/sugarcss/sass/sugar/_sugar.scss:40
@import 'vendors/sassdash/sassdash';
^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/project/build/webpack.base.conf.js:96:17)
    at Module._compile (module.js:571:32)
```

**Comment by ai** [comment]
`sugarss`, not `sugarCss`

**Comment by chovy** [comment]
woops.
