### ISSUE TITLE
npm ERR! peerinvalid Peer vue-loader@7.1.1 wants css-loader@^0.21.0

### ISSUE THREAD

**Issue by osomdevrepos** [vuejs/vue-loader#75]
npm install --save-dev --force vue-loader 
npm WARN using --force I sure hope you know what you are doing.
npm WARN peerDependencies The peer dependency css-loader@^0.21.0 included from vue-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 4.1.12-1-default
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "--force" "vue-loader"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package css-loader@0.23.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vue-loader@7.1.1 wants css-loader@^0.21.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osom/WebstormProjects/ToolBox/npm-debug.log

Anyway to solve this? i tried with --force install but have no luck.

While i installed css-loader@^0.21.0 instead of css-loader@0.23.0 and it worked, but i would want to be able to use the last versions of other dependencies.

Thanks in advance

EDITED: 

It didn't work installing css-loader@^0.21.0 because this Error: Unsupported previous source map format:

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-6707f630&file=app.vue!./~/postcss-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue
Module build failed: Error: Unsupported previous source map format: {"version":3,"sources":["app.vue"],"names":[],"mappings":"AAAA;QACQ,eAAqC;QAArC,+BAAqC;KACxC","file":"app.vue","sourcesContent":["h2{\n        color: color(blueviolet alpha(-60%));\n    }"]}
    at PreviousMap.loadMap (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/node_modules/postcss/lib/previous-map.js:86:23)
    at new PreviousMap (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/node_modules/postcss/lib/previous-map.js:31:25)
    at new Input (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/node_modules/postcss/lib/input.js:39:19)
    at parse (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/node_modules/postcss/lib/processor.js:36:16)
    at Object.module.exports (/home/osom/WebstormProjects/ToolBox/node_modules/vue-loader/lib/style-rewriter.js:75:6)
 @ ./~/style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-6707f630&file=app.vue!./~/postcss-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue 4:14-259 13:2-17:4 14:20-265

**Comment by yyx990803** [comment]
Will be fixed in 7.1.2
