### ISSUE TITLE
vue-loader 8.x 版本不兼容 webpack 2.x

### ISSUE THREAD

**Issue by yanjb** [vuejs/vue-loader#751]
因为项目使用了 vue 1.x 版本，在安装了最新版的 webpack 2.x 版本之后，导致编译报错。
排查发现是因为 .vue 文件内部的 style 标签使用了 lang="less" 之后才会报错。

<style lang="less">
body {
	background-color: #f00;
}
</style>

package.json 依赖如下：
{
  "dependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "css-loader": "^0.27.1",
    "less": "^2.7.2",
    "less-loader": "^4.0.0",
    "script-loader": "^0.7.0",
    "style-loader": "^0.16.1",
    "vue": "^1.0.25",
    "vue-hot-reload-api": "^1.3.3",
    "vue-html-loader": "^1.2.2",
    "vue-loader": "^8.5.2",
    "vue-style-loader": "^1.0.0"
  }
}

报错提示如下：
/Users/bobo/fe/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/Users/bobo/fe/node_modules/less/index.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/bobo/fe/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/bobo/fe/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/bobo/fe/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/bobo/fe/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/bobo/fe/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Users/bobo/fe/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Users/bobo/fe/node_modules/webpack/lib/Compilation.js:142:10)
    at factoryCallback (/Users/bobo/fe/node_modules/webpack/lib/Compilation.js:325:11)
    at /Users/bobo/fe/node_modules/webpack/lib/NormalModuleFactory.js:251:4
    at /Users/bobo/fe/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /Users/bobo/fe/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/Users/bobo/fe/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/bobo/fe/node_modules/webpack/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/Users/bobo/fe/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/Users/bobo/fe/node_modules/webpack/lib/NormalModuleFactory.js:197:6)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by qingtong234** [comment]
@yanjb how do you solve this?

**Comment by XinHuaLuFang** [comment]
我的环境是
vue-loader: 11.3.4
webpack: 2.3.2
跑less一切正常

**Comment by qingtong234** [comment]
@XinHuaLuFang 主要问题是之前跑的是vue 1.0的项目，无法使用vue-loader 11.3

**Comment by huangzhiyang166** [comment]
@yanjb 你最后有什么方法解决吗？我也是碰到这个问题，很多业务代码跑在线上，是早期基于vue1.0的，所以vue-loader只能用8.x ，但webpack升级到2.0后，vue-loader 8.x就会报错

**Comment by adreamleet** [comment]
我也碰到了相似的问题，在原有webpack1、vue1项目上升级webpack2.。。不能resolve vue文件中的scss，解决方案：除了node-sass、sass-loader之外还需要再npm install sass；所以可以试试安装less：npm install less。

**Comment by Harx** [comment]
@qingtong234 配置vue的option可以解决。

参考：
- https://vue-loader.vuejs.org/zh-cn/configurations/pre-processors.html
- https://vue-loader.vuejs.org/zh-cn/configurations/advanced.html

```javascript
{
    test: /\.vue$/,
    loader: 'vue-loader',
    options: {
        loaders: {
            less: "vue-style-loader!css-loader!less-loader",
            scss: 'vue-style-loader!css-loader!sass-loader', // <style lang="scss">
            sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax', // <style lang="sass">
        }
    }
},
```
