### ISSUE TITLE
Jade :class and :style be used together will get an error.

### ISSUE THREAD

**Issue by hezedu** [vuejs/vue-loader#845]
12.2.1@vue-loader
1.11.0@jade

### Example:
```vue
<template lang="jade">
div(:class='{test:true}' :style='{color:"red"}')
</template>
```

### Error Log:

ERROR in ./~/.12.2.1@vue-loader/lib/template-compiler?{"id":"data-v-443bd620"}!./~/.12.2.1@vue-loader/lib/template-compi
ler/preprocessor.js?engine=jade!./~/.12.2.1@vue-loader/lib/selector.js?type=template&index=0!./src/cmpt/task-window.vue
Module build failed: SyntaxError: C:\project\src\cmpt\task-window.vue:6
    1|
  > 2| div(:class='test:true' :style='{color:"red"}')
    3|

Unexpected token :
    at Function (<anonymous>)
    at assertExpression (C:\project\node_modules\.1.11.0@jade\lib\lexer.js:30:3)
    at Lexer.attrs (C:\project\node_modules\.1.11.0@jade\lib\lexer.js:676:20)
    at Lexer.next (C:\project\node_modules\.1.11.0@jade\lib\lexer.js:939:15)
    at Lexer.lookahead (C:\project\node_modules\.1.11.0@jade\lib\lexer.js:113:46)
    at Parser.lookahead (C:\project\node_modules\.1.11.0@jade\lib\parser.js:102:23)
    at Parser.peek (C:\project\node_modules\.1.11.0@jade\lib\parser.js:79:17)
    at Parser.tag (C:\project\node_modules\.1.11.0@jade\lib\parser.js:773:22)
    at Parser.parseTag (C:\project\node_modules\.1.11.0@jade\lib\parser.js:759:17)
    at Parser.parseExpr (C:\project\node_modules\.1.11.0@jade\lib\parser.js:211:21)
    at Parser.block (C:\project\node_modules\.1.11.0@jade\lib\parser.js:729:25)
    at Parser.tag (C:\project\node_modules\.1.11.0@jade\lib\parser.js:838:24)
    at Parser.parseTag (C:\project\node_modules\.1.11.0@jade\lib\parser.js:759:17)
    at Parser.parseExpr (C:\project\node_modules\.1.11.0@jade\lib\parser.js:211:21)
    at Parser.parseExpr (C:\project\node_modules\.1.11.0@jade\lib\parser.js:252:21)
    at Parser.parse (C:\project\node_modules\.1.11.0@jade\lib\parser.js:122:25)
 @ ./src/cmpt/task-window.vue 6:2-285

**Comment by hezedu** [comment]
### Solved 
Not just `:class`, other `:*`  and `:style` is same got an error.  

Add a comma and this problem Solved:
```vue
<template lang="jade">
div(:class='test:true' , :style='{color:"red"}')
</template>
```

**Comment by hezedu** [comment]
But if :style aslo have comma , Will got an error.
```vue
<template lang="jade">
div(:class='{test:true}' , :style='{color:"red"}')
</template>
```
